import React, { useMemo, useRef, useState } from 'react'
import { ArchiveRestore, BookOpen, Brain, CalendarDays, Download, FileText, GitCompare, History, Inbox, Network, PenLine, Plus, RotateCcw, Share2, Sparkles, Trash2 } from 'lucide-react'
import { useAgoraStore } from '../store/useAgoraStore'
import { useStudiumData } from '../lib/useStudiumData'
import { downloadText, mediaCitation, mediaToBibtex, mediaToCsv, mediaToMarkdown, parseImportedMedia } from '../lib/exportUtils'
import type { CommonplaceKind, EssayDraft, StudiumData } from '../types/studium'

type Tab = 'commonplace' | 'journal' | 'compare' | 'essays' | 'discoveries' | 'archive'
const tabs: Array<[Tab, React.ElementType, string]> = [['commonplace', Brain, 'Lugares-comuns'], ['journal', CalendarDays, 'Diário'], ['compare', GitCompare, 'Comparar'], ['essays', PenLine, 'Oficina'], ['discoveries', Inbox, 'Descobertas'], ['archive', History, 'Arquivo']]
const field = 'w-full rounded-xl border border-text-primary/15 bg-bg-base/70 px-3 py-2 text-sm text-text-primary outline-none focus:border-accent-gold'
const button = 'inline-flex items-center justify-center gap-2 rounded-xl bg-accent-gold px-4 py-2 text-xs font-bold text-bg-base hover:bg-accent-gold-bright disabled:opacity-40'

export const StudiumView: React.FC = () => {
  const { mediaItems, aprendizados, userProfile, deletedMediaItems, restoreMediaItem, addMedia, addCustomTrail, updateCustomTrail, setActiveTab } = useAgoraStore()
  const { data, addCommonplace, reviewCommonplace, addJournal, addSession, saveEssay, addDiscovery, remove, restore, importData } = useStudiumData()
  const [tab, setTab] = useState<Tab>('commonplace')
  const [kind, setKind] = useState<CommonplaceKind>('Ideia')
  const [title, setTitle] = useState('')
  const [content, setContent] = useState('')
  const [selectedMedia, setSelectedMedia] = useState<string[]>([])
  const [compareIds, setCompareIds] = useState<string[]>(mediaItems.slice(0, 2).map(item => item.id))
  const [essay, setEssay] = useState<Omit<EssayDraft, 'id' | 'updatedAt'> & { id?: string }>({ title: '', thesis: '', arguments: [''], objections: [''], referenceMediaIds: [], content: '', isPublic: false })
  const [discovery, setDiscovery] = useState({ title: '', type: 'Livro', reason: '', sourceUrl: '', status: 'Caixa de entrada' as const })
  const [guidingQuestion, setGuidingQuestion] = useState('')
  const [journal, setJournal] = useState({ studied: '', understood: '', unresolved: '', changed: '', nextStep: '' })
  const [session, setSession] = useState({ mediaId: mediaItems[0]?.id || '', durationMinutes: 25, progressAmount: 0, progressUnit: 'páginas' as const, notes: '', summary: '' })
  const importRef = useRef<HTMLInputElement>(null)
  const due = data.commonplace.filter(entry => new Date(entry.nextReviewAt) <= new Date())
  const compared = compareIds.map(id => mediaItems.find(item => item.id === id)).filter(Boolean)
  const graphStats = useMemo(() => ({ works: mediaItems.length, ideas: data.commonplace.length + aprendizados.length, links: data.commonplace.reduce((sum, item) => sum + item.mediaIds.length, 0) }), [aprendizados.length, data.commonplace, mediaItems.length])

  const submitCommonplace = (event: React.FormEvent) => {
    event.preventDefault(); if (!title.trim() || !content.trim()) return
    addCommonplace({ kind, title: title.trim(), content: content.trim(), mediaIds: selectedMedia, tags: [] }); setTitle(''); setContent('')
  }
  const submitJournal = (event: React.FormEvent) => { event.preventDefault(); addJournal({ date: new Date().toISOString().slice(0, 10), ...journal }); setJournal({ studied: '', understood: '', unresolved: '', changed: '', nextStep: '' }) }
  const importFile = async (file?: File) => {
    if (!file) return
    const text = await file.text()
    if (/\.json$/i.test(file.name)) { try { importData(JSON.parse(text) as Partial<StudiumData>); return } catch { /* try bibliographic formats below */ } }
    const imported = parseImportedMedia(text, file.name); imported.forEach(item => addMedia(item))
  }
  const shareEssay = async () => {
    const text = `# ${essay.title}\n\n## Tese\n${essay.thesis}\n\n${essay.content}`
    if (navigator.share) await navigator.share({ title: essay.title || 'Ensaio Ágora', text })
    else downloadText(`${essay.title || 'ensaio'}.md`, text, 'text/markdown')
  }
  const createQuestionTrail = () => {
    if (!guidingQuestion.trim()) return
    const terms = guidingQuestion.toLocaleLowerCase('pt-BR').split(/\W+/).filter(term => term.length > 3)
    const related = mediaItems.filter(item => [item.titulo, item.sinopse, ...(item.generos || [])].join(' ').toLocaleLowerCase('pt-BR').split(/\W+/).some(word => terms.includes(word))).slice(0, 6)
    const trail = addCustomTrail(`Investigação: ${guidingQuestion.slice(0, 48)}`, 'Trilha criada a partir de uma pergunta orientadora.', related.map(item => item.id), 'Investigação')
    updateCustomTrail(trail.id, { pergunta_central: guidingQuestion.trim(), objetivo: 'Construir uma resposta fundamentada a partir do acervo.', etapas: ['Mapear conceitos', 'Ler obras relacionadas', 'Comparar argumentos', 'Produzir síntese'], projeto_final: 'Ensaio-resposta', criterio_conclusao: 'Responder à pergunta citando ao menos duas obras.' })
    setActiveTab('trilhas')
  }

  return <div className="space-y-6 pb-12">
    <header data-depth-surface="hero" className="journey-hero relative overflow-hidden rounded-2xl p-5 sm:p-7"><span className="depth-glare" aria-hidden="true" /><div className="journey-hero__content relative z-10"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-accent-gold">Studium</p><h2 className="mt-2 font-serif text-3xl font-bold">Laboratório de formação intelectual</h2><p className="mt-2 max-w-2xl text-sm text-text-secondary">Converta obras em memória, relações e produção própria.</p><div className="mt-5 grid grid-cols-3 gap-2 sm:max-w-md">{Object.entries(graphStats).map(([key, value]) => <div key={key} className="rounded-xl border border-text-primary/10 bg-bg-base/40 p-3 text-center"><strong className="font-serif text-xl text-accent-gold">{value}</strong><span className="block text-[9px] uppercase text-text-secondary">{{ works: 'obras', ideas: 'ideias', links: 'conexões' }[key]}</span></div>)}</div></div></header>
    <nav className="grid grid-cols-3 gap-1 rounded-2xl border border-text-primary/10 bg-bg-surface/80 p-1 lg:grid-cols-6" aria-label="Áreas do Studium">{tabs.map(([id, Icon, label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`flex items-center justify-center gap-1.5 rounded-xl px-2 py-2.5 text-[11px] font-semibold ${tab === id ? 'bg-accent-gold text-bg-base' : 'text-text-secondary hover:bg-bg-elevated hover:text-text-primary'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>

    {tab === 'commonplace' ? <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]">
      <form onSubmit={submitCommonplace} className="space-y-3 rounded-2xl border border-text-primary/10 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">Novo registro</h3><select value={kind} onChange={event => setKind(event.target.value as CommonplaceKind)} className={field}>{['Citação','Ideia','Pergunta','Argumento','Contradição','Vocabulário','Referência'].map(value => <option key={value}>{value}</option>)}</select><input value={title} onChange={event => setTitle(event.target.value)} placeholder="Título ou termo" className={field} /><textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Registre a ideia e seu contexto…" rows={5} className={field} /><div className="max-h-32 space-y-1 overflow-auto">{mediaItems.map(item => <label key={item.id} className="flex items-center gap-2 text-xs text-text-secondary"><input type="checkbox" checked={selectedMedia.includes(item.id)} onChange={() => setSelectedMedia(values => values.includes(item.id) ? values.filter(id => id !== item.id) : [...values, item.id])} />{item.titulo}</label>)}</div><button className={button}><Plus className="h-4 w-4" />Guardar</button></form>
      <section className="space-y-3"><div className="rounded-2xl border border-accent-gold/25 bg-accent-gold/5 p-4"><h3 className="font-serif text-lg font-bold">Revisão de hoje · {due.length}</h3>{due.slice(0, 1).map(entry => <article key={entry.id} className="mt-3"><p className="text-xs uppercase text-accent-gold">{entry.kind}</p><h4 className="font-semibold">{entry.title}</h4><p className="mt-2 text-sm text-text-secondary">{entry.content}</p><div className="mt-3 flex gap-2">{([['again','Rever'],['good','Lembrei'],['easy','Fácil']] as const).map(([quality, label]) => <button key={quality} type="button" onClick={() => reviewCommonplace(entry.id, quality)} className="rounded-lg border border-text-primary/15 px-3 py-1.5 text-xs hover:border-accent-gold">{label}</button>)}</div></article>)}</div>{data.commonplace.map(entry => <article key={entry.id} className="rounded-xl border border-text-primary/10 bg-bg-surface p-4"><div className="flex justify-between gap-3"><div><span className="text-[9px] uppercase text-accent-gold">{entry.kind}</span><h4 className="font-semibold">{entry.title}</h4></div><button type="button" onClick={() => remove('commonplace', entry.id)} aria-label="Mover para lixeira"><Trash2 className="h-4 w-4 text-text-secondary" /></button></div><p className="mt-2 text-xs text-text-secondary">{entry.content}</p></article>)}</section>
    </div> : null}

    {tab === 'journal' ? <div className="grid gap-5 lg:grid-cols-2"><form onSubmit={submitJournal} className="space-y-3 rounded-2xl border border-text-primary/10 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">Diário de hoje</h3>{([['studied','O que estudei?'],['understood','O que compreendi?'],['unresolved','O que ainda não compreendi?'],['changed','Qual ideia mudou minha perspectiva?'],['nextStep','O que devo revisar?']] as const).map(([key,label]) => <textarea key={key} value={journal[key]} onChange={event => setJournal(value => ({ ...value, [key]: event.target.value }))} placeholder={label} rows={2} className={field} />)}<button className={button}>Salvar reflexão</button></form><section className="space-y-3"><form onSubmit={event => { event.preventDefault(); if (session.mediaId) addSession(session) }} className="space-y-3 rounded-2xl border border-accent-gold/20 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">Registrar sessão de leitura</h3><select value={session.mediaId} onChange={event => setSession(value => ({ ...value, mediaId: event.target.value }))} className={field}>{mediaItems.map(item => <option key={item.id} value={item.id}>{item.titulo}</option>)}</select><div className="grid grid-cols-2 gap-2"><input type="number" min="1" value={session.durationMinutes} onChange={event => setSession(value => ({ ...value, durationMinutes: Number(event.target.value) }))} className={field} aria-label="Duração em minutos" /><input type="number" min="0" value={session.progressAmount} onChange={event => setSession(value => ({ ...value, progressAmount: Number(event.target.value) }))} className={field} aria-label="Progresso" /></div><textarea value={session.summary} onChange={event => setSession(value => ({ ...value, summary: event.target.value }))} placeholder="Síntese e resposta às perguntas socráticas: tese, pressupostos, objeções…" rows={4} className={field} /><button className={button}>Concluir sessão</button></form>{data.journal.map(entry => <article key={entry.id} className="rounded-xl border border-text-primary/10 bg-bg-surface p-4"><strong>{new Date(entry.date + 'T12:00:00').toLocaleDateString('pt-BR')}</strong><p className="mt-2 text-xs text-text-secondary">{entry.understood || entry.studied}</p></article>)}</section></div> : null}

    {tab === 'compare' ? <section className="space-y-4"><div className="grid gap-2 sm:grid-cols-3">{mediaItems.map(item => <label key={item.id} className="flex items-center gap-2 rounded-xl border border-text-primary/10 bg-bg-surface p-3 text-xs"><input type="checkbox" checked={compareIds.includes(item.id)} disabled={!compareIds.includes(item.id) && compareIds.length >= 3} onChange={() => setCompareIds(ids => ids.includes(item.id) ? ids.filter(id => id !== item.id) : [...ids, item.id])} />{item.titulo}</label>)}</div><div className="grid gap-3 lg:grid-cols-3">{compared.map(item => item ? <article key={item.id} className="rounded-2xl border border-accent-gold/20 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">{item.titulo}</h3><p className="text-xs text-accent-gold">{item.autor_criador} · {item.ano}</p><p className="mt-3 text-sm text-text-secondary">{item.sinopse}</p><div className="mt-3 flex flex-wrap gap-1">{item.generos?.map(tag => <span key={tag} className="rounded-full bg-bg-base px-2 py-1 text-[10px]">{tag}</span>)}</div><p className="mt-4 text-xs"><b>Motivação:</b> {item.motivo_leitura || 'Não registrada'}</p></article> : null)}</div></section> : null}

    {tab === 'essays' ? <div className="grid gap-5 lg:grid-cols-[1fr_.8fr]"><form onSubmit={event => { event.preventDefault(); setEssay(saveEssay(essay)) }} className="space-y-3 rounded-2xl border border-text-primary/10 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">Oficina de ensaios</h3><input value={essay.title} onChange={event => setEssay(value => ({ ...value, title: event.target.value }))} placeholder="Título" className={field} /><textarea value={essay.thesis} onChange={event => setEssay(value => ({ ...value, thesis: event.target.value }))} placeholder="Tese central" rows={2} className={field} /><textarea value={essay.arguments.join('\n')} onChange={event => setEssay(value => ({ ...value, arguments: event.target.value.split('\n') }))} placeholder="Argumentos — um por linha" rows={3} className={field} /><textarea value={essay.objections.join('\n')} onChange={event => setEssay(value => ({ ...value, objections: event.target.value.split('\n') }))} placeholder="Objeções — uma por linha" rows={3} className={field} /><textarea value={essay.content} onChange={event => setEssay(value => ({ ...value, content: event.target.value }))} placeholder="Desenvolva o ensaio…" rows={9} className={field} /><div className="flex flex-wrap gap-2"><button className={button}>Salvar versão</button><button type="button" onClick={shareEssay} className={button}><Share2 className="h-4 w-4" />Compartilhar</button></div></form><section className="space-y-3"><div className="rounded-2xl border border-accent-gold/20 bg-bg-surface p-5"><h3 className="font-serif text-lg font-bold">Referências</h3>{mediaItems.slice(0,5).map(item => <div key={item.id} className="mt-2 text-xs text-text-secondary"><p>{mediaCitation(item, 'ABNT')}</p><button type="button" onClick={() => downloadText(`${item.titulo}.md`, mediaToMarkdown(item), 'text/markdown')} className="text-accent-gold">Exportar Markdown</button></div>)}</div>{data.essays.map(item => <button key={item.id} type="button" onClick={() => setEssay(item)} className="w-full rounded-xl border border-text-primary/10 bg-bg-surface p-4 text-left"><strong>{item.title}</strong><span className="block text-[10px] text-text-secondary">Atualizado em {new Date(item.updatedAt).toLocaleString('pt-BR')}</span></button>)}</section></div> : null}

    {tab === 'discoveries' ? <div className="grid gap-5 lg:grid-cols-2"><form onSubmit={event => { event.preventDefault(); if (discovery.title) addDiscovery(discovery) }} className="space-y-3 rounded-2xl border border-text-primary/10 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">Caixa de descobertas</h3><input value={discovery.title} onChange={event => setDiscovery(value => ({ ...value, title: event.target.value }))} placeholder="Obra, link ou pergunta" className={field} /><input value={discovery.reason} onChange={event => setDiscovery(value => ({ ...value, reason: event.target.value }))} placeholder="Por que quero explorar isto?" className={field} /><input type="url" value={discovery.sourceUrl} onChange={event => setDiscovery(value => ({ ...value, sourceUrl: event.target.value }))} placeholder="Link opcional" className={field} /><button className={button}><Plus className="h-4 w-4" />Adicionar</button><div className="space-y-2 rounded-xl border border-accent-gold/20 bg-accent-gold/5 p-3 text-xs text-text-secondary"><Sparkles className="h-4 w-4 text-accent-gold" /><p>Pergunta orientadora: “Que obras ajudam a compreender {userProfile.objetivo_descoberta || 'o tema que estou estudando'}?”</p><input value={guidingQuestion} onChange={event => setGuidingQuestion(event.target.value)} placeholder="Digite uma pergunta para gerar uma trilha" className={field} /><button type="button" onClick={createQuestionTrail} className={button}>Criar trilha investigativa</button></div></form><section className="space-y-2">{data.discoveries.map(item => <article key={item.id} className="rounded-xl border border-text-primary/10 bg-bg-surface p-4"><div className="flex justify-between"><div><span className="text-[9px] uppercase text-accent-gold">{item.type}</span><h4 className="font-semibold">{item.title}</h4></div><button type="button" onClick={() => remove('discovery', item.id)}><Trash2 className="h-4 w-4" /></button></div><p className="mt-2 text-xs text-text-secondary">{item.reason}</p></article>)}</section></div> : null}

    {tab === 'archive' ? <div className="grid gap-5 lg:grid-cols-2"><section className="space-y-3 rounded-2xl border border-text-primary/10 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">Portabilidade</h3><div className="flex flex-wrap gap-2"><button type="button" className={button} onClick={() => downloadText('agora-acervo.csv', mediaToCsv(mediaItems), 'text/csv')}><Download className="h-4 w-4" />CSV</button><button type="button" className={button} onClick={() => downloadText('agora-referencias.bib', mediaToBibtex(mediaItems))}><BookOpen className="h-4 w-4" />BibTeX</button><button type="button" className={button} onClick={() => downloadText('agora-studium.json', JSON.stringify(data, null, 2), 'application/json')}><FileText className="h-4 w-4" />Backup</button><button type="button" className={button} onClick={() => importRef.current?.click()}><ArchiveRestore className="h-4 w-4" />Importar</button><input ref={importRef} type="file" accept=".json,.csv,.bib,.ris,application/json,text/csv" className="hidden" onChange={event => void importFile(event.target.files?.[0])} /></div><p className="text-[10px] text-text-secondary">Compatível com JSON, CSV (Goodreads/Letterboxd), BibTeX e RIS.</p><h4 className="pt-3 font-semibold">Lixeira recuperável · 30 dias</h4>{deletedMediaItems.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg bg-bg-base p-3 text-xs"><span>{item.media.titulo}</span><button type="button" onClick={() => restoreMediaItem(item.id)} className="text-accent-gold" aria-label={`Restaurar ${item.media.titulo}`}><RotateCcw className="h-4 w-4" /></button></div>)}{data.trash.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg bg-bg-base p-3 text-xs"><span>{item.label}</span><button type="button" onClick={() => restore(item.id)} className="text-accent-gold"><RotateCcw className="h-4 w-4" /></button></div>)}</section><section className="rounded-2xl border border-text-primary/10 bg-bg-surface p-5"><h3 className="font-serif text-xl font-bold">Histórico</h3><div className="mt-3 space-y-2">{data.history.map(item => <div key={item.id} className="border-l border-accent-gold/30 pl-3 text-xs"><strong>{item.action}</strong><p className="text-text-secondary">{item.label} · {new Date(item.timestamp).toLocaleString('pt-BR')}</p></div>)}</div></section></div> : null}
  </div>
}
